#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'almostSorted' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

def almostSorted(arr):
    sorted_arr=sorted(arr)
    diff=[]
    for i in range(len(arr)):
        if arr[i]!=sorted_arr[i]:
            diff.append(i)
    if len(diff)==0:
        print("yes")
    elif len(diff)==2:
        print("yes")
        print("swap",diff[0]+1,diff[1]+1)
    else:
        l,r=diff[0],diff[-1]
        sub=arr[l:r+1]
        if sub[::-1]==sorted_arr[l:r+1]:
            print("yes")
            print("reverse",l+1,r+1)
        else:
            print("no")
    
            
            
            
        
        

if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    almostSorted(arr)
