#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'timeConversion' function below.
#
# The function is expected to return a STRING.
# The function accepts STRING s as parameter.
#

def timeConversion(s):
    period = s[-2:]        # AM or PM
    time_part = s[:-2]     # HH:MM:SS
    hh, mm, ss = time_part.split(":")

    if period == "AM":
        if hh == "12":
            hh = "00"
    else:  # PM
        if hh != "12":
            hh = str(int(hh) + 12)

    return f"{hh}:{mm}:{ss}"
    # Write your code here

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = timeConversion(s)

    fptr.write(result + '\n')

    fptr.close()
